# Generated by Django 4.2.4 on 2023-08-14 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webersems', '0002_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='credit_hours',
            field=models.CharField(default=3, max_length=1),
        ),
    ]
