# Generated by Django 4.2.4 on 2023-08-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webersems', '0003_classe_credit_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='fa',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='classe',
            name='sp',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='classe',
            name='su',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
