# Generated by Django 4.2.4 on 2023-08-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webersems', '0004_classe_fa_classe_sp_classe_su'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='fa',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='sp',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='su',
        ),
        migrations.AlterField(
            model_name='classe',
            name='school',
            field=models.CharField(choices=[('MATH', 'MATH'), ('CS', 'CS'), ('ENGL', 'ENGL'), ('ETC', 'ETC'), ('COMM', 'COMM'), ('LIBS', 'LIBS'), ('BTNY', 'BTNY'), ('CHEM', 'CHEM')], default='CS', max_length=4),
        ),
    ]
