# Generated by Django 4.2.4 on 2023-08-15 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webersems', '0005_remove_classe_fa_remove_classe_sp_remove_classe_su_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='fa',
            field=models.CharField(choices=[(1, 'YES'), (0, 'NO')], default=1, max_length=1),
        ),
    ]
