# Generated by Django 4.2.4 on 2023-08-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webersems', '0007_alter_classe_fa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_name', models.CharField(max_length=50)),
                ('school', models.CharField(choices=[('MATH', 'MATH'), ('CS', 'CS'), ('ENGL', 'ENGL'), ('ETC', 'ETC'), ('COMM', 'COMM'), ('LIBS', 'LIBS'), ('BTNY', 'BTNY'), ('CHEM', 'CHEM')], default='CS', max_length=4)),
                ('class_num', models.CharField(max_length=4)),
                ('credit_hours', models.CharField(default=3, max_length=1)),
                ('fa', models.IntegerField(choices=[(1, 'YES'), (0, 'NO')], default=1)),
            ],
        ),
    ]
