# Generated by Django 4.2.4 on 2023-08-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webersems', '0012_alter_classe_credit_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='spring_semester',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO')], default=1),
        ),
        migrations.AddField(
            model_name='classe',
            name='summer_semester',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO')], default=1),
        ),
    ]
