# Generated by Django 4.2.4 on 2023-08-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webersems', '0014_alter_classe_credit_hours_alter_classe_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='prereq',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='classe',
            name='school',
            field=models.CharField(choices=[('MATH', 'MATH'), ('CS', 'CS'), ('ENGL', 'ENGL'), ('ETC', 'ETC'), ('COMM', 'COMM'), ('LIBS', 'LIBS'), ('BTNY', 'BTNY'), ('CHEM', 'CHEM')], default='CS', max_length=4),
        ),
    ]
