# Generated by Django 4.2.4 on 2023-08-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webersems', '0015_classe_prereq_alter_classe_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='prereq',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
