# Generated by Django 4.2.4 on 2023-08-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webersems', '0016_alter_classe_prereq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='prereq',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
