# Generated by Django 4.2.4 on 2023-08-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webersems', '0017_alter_classe_prereq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classe',
            options={'ordering': ('school', 'class_num')},
        ),
        migrations.RemoveField(
            model_name='semester',
            name='classes',
        ),
        migrations.AddField(
            model_name='semester',
            name='class1',
            field=models.CharField(blank=True, choices=[], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='class2',
            field=models.CharField(blank=True, choices=[], max_length=8, null=True),
        ),
    ]
