# Generated by Django 4.2.4 on 2023-08-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webersems', '0019_remove_semester_class2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='class1',
            field=models.CharField(blank=True, choices=[['CS1030', 'CS1030']], max_length=8, null=True),
        ),
    ]
