# Generated by Django 4.2.4 on 2023-08-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webersems', '0020_alter_semester_class1'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeMajor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_name', models.CharField(max_length=100)),
                ('classes', models.CharField(max_length=5000)),
            ],
        ),
        migrations.AlterField(
            model_name='semester',
            name='class1',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
