# Generated by Django 4.2.4 on 2023-08-16 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webersems', '0021_collegemajor_alter_semester_class1'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='class2',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='class3',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='class4',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='class5',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
