# Generated by Django 4.2.4 on 2023-08-16 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webersems', '0022_semester_class2_semester_class3_semester_class4_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classe',
            new_name='Courses',
        ),
        migrations.DeleteModel(
            name='CollegeMajor',
        ),
    ]
