# Generated by Django 4.2.4 on 2023-08-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webersems', '0023_rename_classe_courses_delete_collegemajor'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='class1_ch',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
    ]
