# Generated by Django 4.2.4 on 2023-08-17 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webersems', '0024_semester_class1_ch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='id',
        ),
        migrations.AddField(
            model_name='semester',
            name='courses_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webersems.courses'),
            preserve_default=False,
        ),
    ]
