# Generated by Django 4.2.4 on 2023-08-17 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webersems', '0025_remove_semester_id_semester_courses_ptr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='class1_ch',
        ),
    ]
