# Generated by Django 4.2.4 on 2023-08-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webersems', '0026_remove_semester_class1_ch'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='credit_hour1',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=4),
        ),
    ]
