# Generated by Django 4.2.4 on 2023-08-17 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webersems', '0027_semester_credit_hour1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='credit_hour1',
        ),
    ]
